### ISSUE TITLE
ページ結合をした時に結合元が2ページ以上あるとすべてが結合されるためページ指定の結合がしたい

### ISSUE THREAD

**Issue by Tkoshi000** [HiraokaHyperTools/PdfNup#2]
"C:\Program Files (x86)\PdfNup\PdfNup.exe"  compose 1200x850 "E:\test\pdfnup.pdf"  ( 0,0 590,0 )  "E:\test\left.pdf"  "E:\test\right.pdf"

上記コマンドで下記の添付ファイルを使用すると、pdfnupのような結果になります。
http://dd7:543/hdb/Showr.aspx?ID=30706

ページ番号を指定して結合することは可能でしょうか

**Comment by kenjiuno** [comment]
0.3 で対応
